# Generated by Django 3.2.9 on 2021-12-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='ClassInteraction',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='SubjectClarity',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='teachingSkill',
        ),
        migrations.AddField(
            model_name='feedback',
            name='response',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
