# Generated by Django 3.2.9 on 2021-12-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0003_auto_20211208_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='batch',
            field=models.TextField(),
        ),
    ]
