# Generated by Django 3.2.9 on 2021-12-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0004_alter_feedback_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='response',
            new_name='response1',
        ),
        migrations.AddField(
            model_name='feedback',
            name='response2',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='response3',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='response4',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='response5',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
