# Generated by Django 3.2.9 on 2021-12-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0005_auto_20211208_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='response1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response5',
            field=models.IntegerField(),
        ),
    ]
